---
title: "Week 1"
author: "Tad Dallas"
includes:
  in_header:
    - \usepackage{lmodern}
output:
  pdf_document:
    fig_caption: yes
    fig_height: 6
    fig_width: 6
    toc: yes
  html_document:
    fig_caption: yes
    fig_height: 6
    fig_width: 6
    highlight: tango
    theme: journal
---





## Structure of the class

### Syllabus 

We will go over this the first day of class. The first week will be no recorded lectures, and then the second week we will dive into the course design of 1 recorded lecture and 1 discussion/deep dive/clarification lecture. 





### My expectations

+ I expect that you apply yourself in an earnest attempt to learn the material. Everyone learns at their own pace, but I take it that if you were not interested in the material, you would not have signed up for the class? I think everyone here is excited to learn R and more about issues around reproducibility. 

+ I expect that you treat other students in the course fairly. I will not tolerate any form of discrimination or disparaging remarks to your colleagues. 

+ I expect that you do your own work. Every coder writes code differently. If I see the same code from two different people, it is a huge red flag. I will not accept copying of code, even if the original code was in the creative commons (you will get this joke later in the course if you do not understand now). 







### Your expectations

We will discuss these in the lecture. I would say 'think-pair-share', but I have no idea how to do that with Zoom. 







## What is R?

Computational programming language that is quite useful to analyse, simulate, understand, and visualize data.




## Why do we use R as ecologists?

Ecology is not just fieldwork. Ecologists attempt to understand species interactions, but in order to generalize across different places, we need theoretical development, which often requires comptuational programming languages like R. Further, in order to analyze field data to gain insight, computing is necessary. I once stated during a panel discussion that I thought every ecologist should know how to program in at least one language, and I certainly stand by it. 


Many people become interested in ecology because they love nature. This is cool. What I would like to communicate though is that you can also love computers or mathematics and get into ecology. 






## Installing R

If you want to, here are the resources.

https://www.r-project.org







